/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c78582ca-f8d9-4dad-9174-88f6e70b8e1a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_xMSYsmVai",
    "aws_user_pools_web_client_id": "dgit132v05v8qeu4srt8uqjkh",
    "oauth": {}
};


export default awsmobile;
